version: '3.2'

volumes:
  SpringDocker-postgreSQL:
    driver: local


services:
  postgres:
    image: postgres:latest
    container_name: SpringDocker-postgreSQL
    volumes:
      - type: volume
        source: SpringDocker-postgreSQL
        target: /Volumes/MacOS/Docker/SQL/postgreSQL_base/
    environment:
      POSTGRES_DB: Users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5433:5432"

#jdbc:postgresql://localhost:5433/SpringDocker